apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DB: bGxt    # Base64 encoded value of 'postgres_db'
  POSTGRES_USER: Y29kZQ==  # Base64 encoded value of 'postgres_user'
  POSTGRES_PASSWORD: MUFGVVNHbEp1anpyTGdzNWlpdEhXN0J1eGk0cGtVS2g=  # Base64 encoded value of 'secure_password'
  REDIS_PORT: NjM3OQ==             # Base64 encoded value of '6379'