apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ include "llm-app.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "llm-app.selectorLabels" . | nindent 6 }}

