{{- if .Values.celery.beat.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.celery.beat.componentName }}
  labels:
    {{- include "llm-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.celery.beat.componentName }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.celery.beat.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llm-app.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.celery.beat.strategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "llm-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.celery.beat.componentName }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llm-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{-  with .Values.celery.beat.command }}
          command: ["/bin/sh"]
          args:
              - -c
              - >-
                  {{ . }}
          {{- end }}
          {{- include "llm-app.envVariables" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}